ci(tag-release): abort when no unreleased commits are found
```text
$ ./tag-release 1.0.10 'fix something()'

ERROR: No unreleased commits found since the last tag, 1.0.9

7420d14 - (tag: 1.0.9, origin/main) release: 1.0.9 - fix git_guess_default_branch() (25 hours ago) <Victor Payno>
a251bd4 - chore: add a checkout refresh script (25 hours ago) <Victor Payno>
ab11d55 - fix(git-helpers-lib): move default branch guess to else branch in git_guess_default_branch() (25 hours ago) <Victor Payno>
3795f62 - fix(install-git-aliases): add verbosity to script (3 days ago) <Victor Payno>
a26aa96 - docs: move Releases section before Helpers section (3 days ago) <Victor Payno>

```

```text
$ ./tag-release 1.0.10 'fix something()'

release: 1.0.10 - fix something()

Unreleased commits:

f1b3017 - (HEAD -> main) ci(tag-release): abort when no unreleased commits are found (46 seconds ago) <Victor Payno>

Are you sure you want to tag and release?

              Yes        No

```

diff --git a/tag-release b/tag-release
--- a/tag-release
+++ b/tag-release
@@ -20,6 +20,41 @@ fi
 
 declare tag_message="release: ${tag_version} - ${tag_note}"
 
+declare current_branch
+current_branch="$(git branch --show-current)"
+
+declare current_remote
+current_remote="$(git rev-parse --abbrev-ref --symbolic-full-name "@{u}" | cut -f1 -d'/')"
+
+declare previous_tag
+previous_tag="$(git tag --list -n0 | tail -n1)"
+
+declare -i unreleased_commit_count=0
+
+# Can't reliably use wc because the last log line doesn't end with a new line.
+# So 0 and 1 commits are indistinguishable from each other.
+# format: ^6e5f52e - (HEAD -> main) ci(tag-release): abort when no unreleased commits are found (3 minutes ago) <Victor Payno>$
+unreleased_commit_count="$(git log --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit --decorate "${previous_tag}".. | grep -c -E '[a-z0-9]+\s+-')"
+
+if [[ ${unreleased_commit_count} -eq 0 ]]; then
+	printf "\n"
+	printf "ERROR: No unreleased commits found since the last tag, %s\n" "${previous_tag}"
+	printf "\n"
+	git log --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit --decorate -n 5
+	printf "\n\n"
+	exit 1
+fi
+
+printf "\n"
+printf "%s\n" "${tag_message}"
+printf "\n"
+printf "Unreleased commits:\n"
+printf "\n"
+git log --pretty=format:'%h -%d %s (%cr) <%an>' --abbrev-commit --decorate "${previous_tag}"..
+printf "\n"
+
+gum confirm "Are you sure you want to tag and release?" || exit
+
 declare release_message
 read -r -d '' release_message <<-EOF
 	$(git-cliff --strip header --unreleased --tag "${tag_version}")
@@ -40,12 +75,6 @@ printf "\n"
 echo Running: git show "${tag_version}"
 git show "${tag_version}"
 printf "\n"
-
-declare current_branch
-current_branch="$(git branch --show-current)"
-
-declare current_remote
-current_remote="$(git rev-parse --abbrev-ref --symbolic-full-name "@{u}" | cut -f1 -d'/')"
 
 printf "\n"
 printf "Staged commits:\n"
